from pathlib import Path
import os

# HOME_DIR = f"{os.path.expanduser("~")}"

# Using rootless docker?
ROOTLESS = True
if ROOTLESS :
    # If so; change this
    SOCKET = "unix:///run/user/1000/docker.sock"

VIRTUOSO_DIR_FALLBACK = None # f'{HOME_DIR}/.rdf-data'

VIRTUOSO_DIR = os.getenv('VIRTUOSO_DIR', default=VIRTUOSO_DIR_FALLBACK)

assert(VIRTUOSO_DIR is not None), "Please set VIRTUOSO_DIR in config.py (or by setting variable in shell); dir will contain all virtuoso databases generated by virtuoso wrapper"

VIRTUOSO_DIR = Path(VIRTUOSO_DIR)