[project]
name = "shape-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Koen Jacobs", email = "koen.jacobs@redpencil.io" }
]
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "rdflib>=7.6.0",
    "shexer>=2.7.2.1",
    "sparqlwrapper>=2.0.0",
    "typer>=0.24.1",
]

[project.scripts]
# shape-gen = "shape_gen:main"
voicl = "shape_gen.voicl.generator:voicl_typer"
virtuoso = "shape_gen.virtuoso.cli:virtuoso_typer"
void = "shape_gen.void:void_typer"

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
source.include = ['assets/virtuoso.ini', '/voicl/templates/*.sparql']
